check argument

diff --git a/add b/add
--- a/add
+++ b/add
@@ -1,1 +1,7 @@
 #!/bin/bash
+c=${0%/*}/config ; source "$c" ; if [ $? -ne 0 ] ; then echo "Error: no config file $c" 1>&2 ; exit 1 ; fi
+
+if [ -z "$1" ] ; then echo " Usage: add <host> " ; exit 1 ; fi
+
+HOST=$1;
+
